### ISSUE TITLE
The road to 1.0

### ISSUE THREAD

**Issue by jcupitt** [ImagingDataCommons/libdicom#11]
This issue is to track progress towards a 1.0 public release.

- [x] Look through dicom-file and dicom-data and do a cleanup. I think there are a few things there I'd like to change a little.
- [ ] I think it'd be a good idea to make a very quick prototype Python binding using cffi. It shouldn't be much work, and it would reveal any "duh" moments in the API. Fixing stuff like that after we hit 1.0 is *much* harder.
- [x] #19
- [x] Perhaps make a tiny website for the project in gh-pages? If we have API docs in markdown, it's only an hour or so of work.
- [ ] Include a demonstration of useful performance improvements over existing dicom readers to motivate interest.
- [ ] Add a DICOM reader to libvips based on libdicom?
- [ ] [vipsdisp](https://github.com/jcupitt/vipsdisp) would then get a DICOM loader too, also a potentially useful tool. 
- [ ] Launch 1.0, announce on twitter, image.sc, etc.

Please edit and add / remove any of these suggestions, of course.

**Comment by hackermd** [comment]
Documentation is now available online at Read the Docs: ttps://libdicom.readthedocs.io

**Comment by jcupitt** [comment]
A quick update: I've got Leica DICOMs working in my fork. I'll make a PR on openslide in a week or two after I polish it a bit.

Here's the standard Leica DICOM being viewed:

![image](https://user-images.githubusercontent.com/580843/234259042-cb0d0cae-b0ed-4004-ac40-806695797407.png)

It's a bit slow (I'll try to improve that). 

It looks very washed out due to no colour management. Here's the same slide with and without a profile:

![image](https://user-images.githubusercontent.com/580843/234258814-4112c603-9fe6-4f0b-aa1c-2dc636199d39.png)

**Comment by jcupitt** [comment]
There's a proposed 1.0 here: https://github.com/jcupitt/libdicom currently awaiting merge to this repo.

It implements all these ideas. I'll close this issue.
