### ISSUE TITLE
Use of `size_t`/`ssize_t` in `dicom.h`

### ISSUE THREAD

**Issue by bgilbert** [ImagingDataCommons/libdicom#21]
`contributing.rst` says:

> To facilitate portability, the `dicom.h` header file is restricted to
> 
> * C99 version of the standard (C89 + Boolean type from ``stdbool.h`` + fixed-width integer types from ``stdint.h``/``inttypes.h``)
> * Clear, exact-width integer types (``int16_t``, ``int32_t``, ``int64_t``, ``uint16_t``, ``uint32_t``, and ``uint64_t``)

But in fact, `dicom.h` includes several references to `size_t` and `ssize_t`.

**Comment by hackermd** [comment]
Good point @bgilbert! We should probably use `uint64_t` for the frame offsets.

The basic offset table is limited to 32-bit unsigned integer values, but we may want to allow the `DcmBOT` type to hold values of the [Extended Offset Table](https://dicom.nema.org/medical/dicom/current/output/chtml/part06/chapter_6.html#para_77685ef1-f91c-402a-886c-6f80d350aaaa) attribute, which has Value Representation [OV](https://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_6.2.html#para_6f799eb8-e8bc-48ba-a27f-52b9573c13db). See [CP 1818](https://dicom.nema.org/Dicom/News/January2019/docs/cpack99/cp1818.pdf) for context.
