### ISSUE TITLE
Consider renaming `master` branch to `main`

### ISSUE THREAD

**Issue by bgilbert** [ImagingDataCommons/libdicom#28]
The community as a whole is moving away from `master`, and `main` seems to be a common choice.  Now would be a good time to do it, before the library gets more adoption.

GitHub allows fairly transparent branch renaming from [this page](https://github.com/hackermd/libdicom/settings/branches), though cloned repos would need to be updated manually.

**Comment by hackermd** [comment]
Fine with me. We will need to update a few things (Read the Docs, etc.) but that should be relative straightforward. Shall we first finalize the currently open pull requests and then rename?

**Comment by bgilbert** [comment]
There's actually no requirement that we land the outstanding pull requests first (GitHub will automatically update the target branch) so this could be done at any time.
