### ISSUE TITLE
Repository configuration

### ISSUE THREAD

**Issue by bgilbert** [ImagingDataCommons/libdicom#33]
After the move to ImagingDataCommons, it appears the repository configuration has changed a bit.  I have some limited access to the repo settings, so I've made these changes:

- Disabled the Discussions, Wiki, and Projects features, since we're not currently using them.  (But disabling Projects didn't remove the tab for some reason?)
- Disabled squash and rebase merging on PRs.  We've been using merge commits, and consistency is good.

I can revert any of those changes if desired.

It'd be good to enable branch protection and required checks, too, but I don't have access to do that.

**Comment by hackermd** [comment]
The repository is now under an organization, which gives us finer control over repository settings. The master branch is protected and required checks should be in place. We can further fine tune those settings if desired.

**Comment by hackermd** [comment]
@bgilbert you also suggested to rename `master` to `main` (#28). Maybe now would be a good time to do that?

**Comment by bgilbert** [comment]
After required checks are enabled, individual checks need to be manually added to the required list.  You'd need to search for each of the three checks in the search box, add them, then save the branch protection settings.

Renaming the branch sounds good.  I don't have access to do that myself, but I think you can go ahead when ready.

**Comment by bgilbert** [comment]
(You may want to disable "require branches to be up-to-date before merging".  I think it's on by default, and it can require extra rebasing that seems pointless for a project of this size.)

**Comment by hackermd** [comment]
This setting appears to be disabled. I disabled the parent setting to be sure.

**Comment by hackermd** [comment]
@bgilbert let me know if you would like add further checks.

**Comment by bgilbert** [comment]
It looks like only the macOS one is marked required currently.  I'd be in favor of making the Ubuntu and Windows ones required also.

**Comment by hackermd** [comment]
Good catch. I thought it would add all three at once. All three should be required now.
