### ISSUE TITLE
wrong tag for AS check?

### ISSUE THREAD

**Issue by jcupitt** [ImagingDataCommons/libdicom#42]
Hey @hackermd, sorry to ping you, I'm not sure I have a current email address for you :(

I'm revising the parser and tests and noticed this:

https://github.com/ImagingDataCommons/libdicom/blob/main/tests/check_dicom.c#L210-L214

Could this be a copy-paste typo from the previous test? Should the tag be `0x00101010`?

**Comment by jcupitt** [comment]
Yes, looks like there was an error in the test suite.

**Comment by hackermd** [comment]
Sorry for the delayed response @jcupitt. Glad you found the error.
