### ISSUE TITLE
Bug - Floating point exception

### ISSUE THREAD

**Issue by voidz0r** [ImagingDataCommons/libdicom#83]
# Introduction
The issue comes whenever a zero value is passed to one of the width,height parameter of the tile.

https://github.com/ImagingDataCommons/libdicom/blob/345eda55428b04182233615afeaa10ce10a0cbe1/src/dicom-file.c#L335-L363

Debugging it with gdb shows the following:
![02_floating_point_exception](https://github.com/ImagingDataCommons/libdicom/assets/1032286/d76ee67d-987b-41a0-addd-7f4318789ee7)

With the value of width and frame_width set to 0.
![03_breakpoint](https://github.com/ImagingDataCommons/libdicom/assets/1032286/ac79db76-3c67-4845-9d01-bd2c48d86f0f)

This is possible by crafting a DCM file with the following byte sequences:
![04_hex](https://github.com/ImagingDataCommons/libdicom/assets/1032286/801fb21d-e1b9-4e05-8520-a21765afdc3e)

# Impact
The application just crashes with no further consequence. This issue does not seem to affect related products such as openslide.

# Solution
The solution would be to check if the provided values are different from zero, and returns an error whenever this happens.

Attached the payload: 

[floatpe.zip](https://github.com/ImagingDataCommons/libdicom/files/14313026/floatpe.zip)

**Comment by jcupitt** [comment]
I fixed this with https://github.com/ImagingDataCommons/libdicom/commit/17d7e756a4f57a22caa7f4d54b34adcef957cf68 and credited you in the change (I hope that's OK).

Thank you for the very clear bug report!

**Comment by jcupitt** [comment]
I did a little quick grepping and I couldn't see any similar /0 issues.

**Comment by voidz0r** [comment]
Looks good to me. Thanks for the mention in the changelog :)
