### ISSUE TITLE
Extended Offset Table not used if Per Frame Functional Groups Sequence is missing

### ISSUE THREAD

**Issue by pcram-techcyte** [ImagingDataCommons/libdicom#91]
We use libdicom to read dicom files from a remote filesystem.  We've noticed that getting a frame out of some of our DICOM files takes a long time, even though those files have an Extended Offset Table:

```
./builddir/dcm-getframe -V -o frame.jpg test_file.dcm 10000
INFO     [Tue Oct  1 18:12:44 2024] - Read filehandle 'test_file.dcm'
INFO     [Tue Oct  1 18:12:44 2024] - Read frame 10000
INFO     [Tue Oct  1 18:12:44 2024] - Building offset table from pixel data scan. 
INFO     [Tue Oct  1 18:12:44 2024] - frame number = 10000
…
```

If I add an empty Per Frame Functional Groups Sequence via pydicom (`python3 -c "import pydicom; ds = pydicom.dcmread('test_file.dcm'); ds.PerFrameFunctionalGroupsSequence = []; ds.save_as('test_file_modified.dcm')"`), then dcm-getframe runs much faster (30ms vs 500ms locally) and it no longer says "Building offset table from pixel data scan":

```
./builddir/dcm-getframe -V -o frame.jpg test_file_modified.dcm 10000
INFO     [Tue Oct  1 18:14:32 2024] - Read filehandle 'test_file_modified.dcm'
INFO     [Tue Oct  1 18:14:32 2024] - Read frame 10000
INFO     [Tue Oct  1 18:14:32 2024] - frame number = 10000
...
```

From what I can tell, the extended offset table gets parsed in `dcm_filehandle_prepare_read_frame`.  I walked through this with my (unmodified) test file and noted `read_extended_offsets` was never called because `filehandle->last_tag` was [not equal to TAG_EXTENDED_OFFSET_TABLE](https://github.com/ImagingDataCommons/libdicom/blob/60f291dea0fd464e34d693b1ad55c46f9f2ee69a/src/dicom-file.c#L1204).  Going up to the top of `dcm_filehandle_prepare_read_frame`, it calls [`dcm_filehandle_get_metadata_subset`](https://github.com/ImagingDataCommons/libdicom/blob/60f291dea0fd464e34d693b1ad55c46f9f2ee69a/src/dicom-file.c#L1157), which seeks ahead until it gets to one of the stop_tags, but [TAG_EXTENDED_OFFSET_TABLE isn't in that list](https://github.com/ImagingDataCommons/libdicom/blob/60f291dea0fd464e34d693b1ad55c46f9f2ee69a/src/dicom-file.c#L816) so it ends up skipping over that tag and not stopping until it gets to the pixel data.  Then when we return back to `dcm_filehandle_prepare_read_frame` and try to seek forward to the TAG_EXTENDED_OFFSET_TABLE tag, we've already moved past it.

I [fixed this](https://github.com/ImagingDataCommons/libdicom/pull/92) by adding TAG_EXTENDED_OFFSET_TABLE to the list of[ stop_tags at the top of dcm_filehandle_get_metadata_subset](https://github.com/ImagingDataCommons/libdicom/blob/60f291dea0fd464e34d693b1ad55c46f9f2ee69a/src/dicom-file.c#L816).  Is that the best way to fix it?

**Comment by jcupitt** [comment]
Hi @pcram-techcyte, thanks for this, it sounds like a good solution.

Just so I can check, do you have a sample file which shows this behaviour?

**Comment by jcupitt** [comment]
I checked with the sample file that @pcram-techcyte kindly emailed and this fix works well. The linked PR has been merged.

Thank you again for finding this issue.
